import type { IncomingMessage, ServerResponse } from 'http'
import type { SSRContext } from '@vue/server-renderer'
import { renderToString } from '@vue/server-renderer'
import manifest from 'ssr:manifest'
import template from 'ssr:template'

import { createApp } from './main'

type Manifest = Record<string, string[]>

function renderPreloadLink(file: string): string {
  if (file.endsWith('.js')) {
    return `<link rel="modulepreload" crossorigin href="${file}">`
  }
  if (file.endsWith('.css')) {
    return `<link rel="stylesheet" href="${file}">`
  }
  if (file.endsWith('.woff')) {
    return `<link rel="preload" href="${file}" as="font" type="font/woff" crossorigin>`
  }
  if (file.endsWith('.woff2')) {
    return `<link rel="preload" href="${file}" as="font" type="font/woff2" crossorigin>`
  }
  if (file.endsWith('.gif')) {
    return `<link rel="preload" href="${file}" as="image" type="image/gif">`
  }
  if (file.endsWith('.jpg') || file.endsWith('.jpeg')) {
    return `<link rel="preload" href="${file}" as="image" type="image/jpeg">`
  }
  if (file.endsWith('.png')) {
    return `<link rel="preload" href="${file}" as="image" type="image/png">`
  }
  // TODO
  return ''
}

function renderPreloadLinks(modules: string[], manifest: Manifest): string {
  let links = ''
  const seen = new Set<string>()

  modules.forEach((id: string) => {
    const files = manifest[id]
    if (files) {
      files.forEach((file: string) => {
        if (!seen.has(file)) {
          seen.add(file)
          links += renderPreloadLink(file)
        }
      })
    }
  })

  return links
}

export async function render(): Promise<string> {
  const { app } = createApp()

  // passing SSR context object which will be available via useSSRContext()
  // @vitejs/plugin-vue injects code into a component's setup() that registers
  // itself on ctx.modules. After the render, ctx.modules would contain all the
  // components that have been instantiated during this render call.
  const ctx: SSRContext = {}
  const appHtml = await renderToString(app, ctx)

  // the SSR manifest generated by Vite contains module -> chunk/asset mapping
  // which we can then use to determine what files need to be preloaded for this
  // request.
  const preloadLinks = renderPreloadLinks(ctx.modules, manifest)

  // inject the template
  return template.replace('</head>', `${preloadLinks}</head>`).replace('<div id="app"></div>', `<div id="app">${appHtml}</div>`)
}

// export createApp
export { createApp }
